### ISSUE TITLE
error on fresh wheezy install

### ISSUE THREAD

**Issue by ysr23** [jpec/pimp#1]
Hi, I'm getting the following when i try to run the script:

pi@raspberrypi ~/pimp $ ./pimp.py 
Traceback (most recent call last):
  File "./pimp.py", line 316, in <module>
    app = curses.wrapper(PiMP)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "./pimp.py", line 125, in **init**
    self.init_curses()
  File "./pimp.py", line 140, in init_curses
    curses.curs_set(0)
_curses.error: curs_set() returned ERR

**Comment by jpec** [comment]
Hi. You need to use Python 3.
